### ISSUE TITLE
Duplicated initiative

### ISSUE THREAD

**Issue by z0ph** [fwdcloudsec/known_aws_accounts#17]
- https://github.com/rupertbg/aws-public-account-ids

The last update on `accounts.json` comes from last year. Checkout if we are missing some piece here.

**Comment by sdemjanenko** [comment]
Permiso's repo was forked from this (https://github.com/Permiso-io/aws-public-account-ids). This PR already took care of merging the missing data: https://github.com/fwdcloudsec/known_aws_accounts/pull/12

**Comment by z0ph** [comment]
Thanks Stephen, wasn't aware of that!
