### ISSUE TITLE
Create similar repo for known ip blocks.

### ISSUE THREAD

**Issue by jonjohnston** [fwdcloudsec/known_aws_accounts#34]
Maybe have similar layout that is the know ips for AWS. For example:
Amazon Cloudfront IPS and Amazon Route53 Healthcheck IPs
https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips
https://ip-ranges.amazonaws.com/ip-ranges.json

**Comment by christophetd** [comment]
AWS IP ranges are dynamic. The best (and documented) way to retrieve them is to use, as you point out, https://ip-ranges.amazonaws.com/ip-ranges.json
