### ISSUE TITLE
Support `deprecated`

### ISSUE THREAD

**Issue by ramimac** [fwdcloudsec/known_aws_accounts#48]
- [x] Add optional field to schema and validator
- [x] Populate
- [x] Remove from titles

> These can instead be in the yaml. Preferably not a deprecated: true because that name would be set in the "negative" instead of "positive" 

```
# simple enabled/disabled, if disabled, assume deprecated
enabled: false
# if this key is set, assume deprecated
deprecated_date: 2025-12-31
```

**Comment by nitrocode** [comment]
A separate file for deprecated entries is also an option
